### ISSUE TITLE
Bug -- Import/Export appears to be broken

### ISSUE THREAD

**Issue by icsy7867** [FoxUSA/StoreDown#36]
I have not been able to successfully import/export (Not a huge deal as I can just backup couchdb instead, but having manual backups might be nice once I get thousands of items...).  Currently YAML export does not work, JSON export does work.

It looks like the function/method for the yaml.safeDump should now just be yaml.dump.  If you edit your:
ImportExport.vue

And update yaml.safeDump to simply yaml.dump
```
        saveAs(new Blob([yaml.dump(errors)], { type: 'text/plain;charset=utf-8' }), 'importErrors.yml')
        saveAs(new Blob([yaml.dump(data.rows)], { type: 'text/plain;charset=utf-8' }), `${this.exportFileName}.yml`)
```

However, imports still arent working, but now yaml export is working, and now allows you to download an error file.
I added this change here:
https://github.com/FoxUSA/StoreDown/pull/37

**Comment by FoxUSA** [comment]
This was fixed in https://github.com/FoxUSA/StoreDown/issues/27, I just haven't gotten around to merging the branch and tagging it yet.

**Comment by icsy7867** [comment]
Neat!  Thanks for responding!  I'll keep an eye out for it.  While I'm getting use to couchdb and your web app, I just don't want to add my hundreds of items and locations and then break couchdb.  So I'm wanting to make sure I have a backup.

**Comment by FoxUSA** [comment]
The JSON dump should still work.
