### ISSUE TITLE
Moving Boxes

### ISSUE THREAD

**Issue by OBoudreaux** [FoxUSA/StoreDown#42]
Is there a way to move a box from one location to another besides yaml export and search/replace?

**Comment by FoxUSA** [comment]
You can use a [prefix](https://github.com/FoxUSA/StoreDown/blob/master/docs/config.schema.md#prefix-example)

For example you can set `box1` to prefix `house/bedroom/`. You can then only type box1 for and it will display `house/bedroom/box1`. You can them move that prefix by updating the config entry
