### ISSUE TITLE
host shouldn't add column if no port is given

### ISSUE THREAD

**Issue by BerkeleyTrue** [FoxUSA/StoreDown#9]
I have a proxy redirect requests to the couchdb through a path prefix (/_db) on the same host. 

Issue:

Adding the host 'storedown.example.com/_db' as the host and the port empty, the frontend attempts to make requests to 'https://storedown.example.com/_db:/storedown/

Expected:

The frontend to connect to couchdb through `https://storedown.example.com/_db/storedown`

**Comment by FoxUSA** [comment]
What proxy do you use by chance?
It makes no difference to this issue just curious.

**Comment by BerkeleyTrue** [comment]
I'm using Traefik

**Comment by FoxUSA** [comment]
@BerkeleyTrue 
I think this will work today based on my [read of the code](https://github.com/FoxUSA/StoreDown/blob/master/src/services/Database.js#L80)

Set the host to `storedown.example.com` and set the database to `_db/storedown`

**Comment by FoxUSA** [comment]
It seems like you have taken your open source rights and [solved it yourself](https://github.com/FoxUSA/StoreDown/commit/3883a69b8c3146dc430899558bed155a1f6d81e5)
